Category Model
Eidenn005/online-book-store pull request #9
Opened 2024-05-20 04:47 UTC by Eidenn005

Added Category and all needed classes
Add changes to Book classes

2024-05-20 20:39 UTC, rel1c-hub approved these changes
LGTM overall, but try adding categories and book categories, or you check if the code works by adding everything by hand in Postman?

2024-05-21 09:26 UTC, yevheniisynytsia requested changes
Great job! Left some comments

2024-05-21 09:26 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/controller/CategoryController.java
> +    public List<CategoryDto> getAll(Authentication authentication, Pageable pageable) {
I guess you don't need `Authentication` here

2024-05-21 09:26 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/dto/CreateCategoryRequestDto.java
> +    private String name;
please validate size to fail on the validation level instead of getting exception from DB

2024-05-21 09:26 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    private Set<Category> categories = new HashSet<>();
please exclude from equals hashcode toString

2024-05-21 09:26 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
>          return bookMapper.toDto(savedBook);
let's also validate category ids that we get from user
A user can pass 498240938409238 and you don't have such in db

2024-05-21 09:26 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        }
if is duplicated, please make a private method

2024-05-24 05:57 UTC, Eidenn005 commented on src/main/java/com/example/onlinebookstore/controller/CategoryController.java
> +    public List<CategoryDto> getAll(Authentication authentication, Pageable pageable) {
Done

2024-05-24 05:57 UTC, Eidenn005 commented on src/main/java/com/example/onlinebookstore/dto/CreateCategoryRequestDto.java
> +    private String name;
done

2024-05-26 14:38 UTC, Eidenn005 commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    private Set<Category> categories = new HashSet<>();
Done

2024-05-26 21:27 UTC, Eidenn005 commented on src/main/java/com/example/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        }
done

2024-05-26 22:00 UTC, Eidenn005 commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
>          return bookMapper.toDto(savedBook);
done

2024-05-27 12:24 UTC, andrii-hoienko approved these changes
Good job!

2024-05-28 07:44 UTC, merged